/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

// Source: https://triageiq-api-242393598566.us-central1.run.app/openapi.json

export interface paths {
    "/triage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Triage
         * @description Triage a GitHub issue and return a structured TriagePlan.
         */
        post: operations["triage_triage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Eval Summary
         * @description Return the static eval methodology summary from reports/eval_summary.json.
         */
        get: operations["eval_summary_eval_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AbstentionStatus
         * @description Selective-prediction gate over existing pipeline signals (ADR-0021).
         *
         *     Priority stage is intentionally absent: priority_guess has no calibrated confidence
         *     signal anywhere in the pipeline to threshold, unlike component_confidence (ADR-0004)
         *     or the CQR interval (ADR-0010). See ADR-0021 for why that gap is flagged, not gated.
         */
        AbstentionStatus: {
            component: components["schemas"]["StageAbstention"];
            resolution: components["schemas"]["StageAbstention"];
        };
        /**
         * ConformalIntervalResult
         * @description CQR-adjusted prediction interval with empirical coverage metadata.
         *
         *     lower_days / upper_days are per-request predictions (raw interval ± Q scalar).
         *     empirical_coverage and CI bounds are fixed per repo from the calibration run.
         *     This is marginal (not conditional) coverage; temporal data may violate exchangeability.
         *     See ADR-0010.
         */
        ConformalIntervalResult: {
            /** Lower Days */
            lower_days: number;
            /** Upper Days */
            upper_days: number;
            /** Target Coverage */
            target_coverage: number;
            /** Empirical Coverage */
            empirical_coverage: number;
            /** Coverage Ci95 Lower */
            coverage_ci95_lower: number;
            /** Coverage Ci95 Upper */
            coverage_ci95_upper: number;
        };
        /**
         * DeclaredAttribution
         * @description LLM-emitted source attribution (elicited by the prompt — contrast GroundingAttribution,
         *     a post-hoc reconstruction of the same plan; ADR-0015/ADR-0020).
         */
        DeclaredAttribution: {
            /**
             * Component Source
             * @enum {string}
             */
            component_source: "classifier_top3" | "model_override";
            /**
             * Component Override Reason
             * @default
             */
            component_override_reason: string;
            /** Summary Cited Issues */
            summary_cited_issues?: number[];
            /** Next Steps Cited Issues */
            next_steps_cited_issues?: number[];
        };
        /**
         * GroundingAttribution
         * @description Reconstruction of what the LLM's TriagePlan already claimed as its sources.
         *
         *     Not new attribution elicited from a prompt change — the prompt is unchanged this
         *     iteration. See ADR-0015.
         */
        GroundingAttribution: {
            /** Component Source */
            component_source: string;
            /** Similar Issue Refs */
            similar_issue_refs: number[];
        };
        /**
         * GroundingStatus
         * @description Deterministic verification of the plan's claims against upstream pipeline outputs.
         *
         *     See src/triage_iq/models/grounding.py:verify_plan_grounding and ADR-0015. Grounding here
         *     means traceable to this pipeline's own classifier_top3 / retrieval outputs for this
         *     request — not verification against world/ground truth.
         */
        GroundingStatus: {
            /** Component Grounded */
            component_grounded: boolean;
            /** Component Reason */
            component_reason: string;
            /** Similar Issue Refs */
            similar_issue_refs: number[];
            /** Ungrounded Refs */
            ungrounded_refs: number[];
            /** All Grounded */
            all_grounded: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Repos Loaded */
            repos_loaded: string[];
            /** Groq Key Present */
            groq_key_present: boolean;
            /** Uptime S */
            uptime_s: number;
        };
        /** SimilarIssue */
        SimilarIssue: {
            /** Number */
            number: number;
            /** Similarity */
            similarity: number;
            /** Relevance Note */
            relevance_note: string;
        };
        /**
         * StageAbstention
         * @description Per-stage selective-prediction gate result (ADR-0021).
         *
         *     Deterministic threshold on an already-computed signal (component_confidence /
         *     grounding_status / CQR interval width) — not a new model. `reason` is empty when
         *     not abstained, else a short machine-readable code ("low_confidence", "ungrounded",
         *     "wide_interval").
         */
        StageAbstention: {
            /** Abstained */
            abstained: boolean;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /**
         * TriagePlan
         * @description Structured triage plan produced by the LLM assistant.
         *
         *     W4 Phase 2 note: expected_resolution_lower_days / expected_resolution_upper_days
         *     are now produced by the de-leaked model trained on a correct created_at split
         *     (CI coverage 77% vs previous 0%). resolution_bucket is an additional field
         *     computed directly from the bucket classifier — it supplements but does not
         *     replace the float fields. The LLM prompt still receives float signals because
         *     empirical eval showed bucket-only prompting regresses judge scores (−0.53 on
         *     resolution_estimate_reasonableness). See ADR-0009 T2.7.
         */
        TriagePlan: {
            /** Predicted Component */
            predicted_component: string;
            /** Component Confidence */
            component_confidence: number;
            /** Similar Issues */
            similar_issues?: components["schemas"]["SimilarIssue"][];
            /** Expected Resolution Summary */
            expected_resolution_summary: string;
            /** Expected Resolution Lower Days */
            expected_resolution_lower_days: number;
            /** Expected Resolution Upper Days */
            expected_resolution_upper_days: number;
            /**
             * Resolution Bucket
             * @description Coarse bucket from ordinal classifier: hours/days/weeks/months/long. Supplemental to the float fields; k8s passes 60% obo threshold, vscode uses naive prior (low confidence). See ADR-0009.
             * @default days
             */
            resolution_bucket: string;
            /**
             * Resolution Confidence Pct
             * @description Bucket classifier confidence (0–100%). Below 40% = low signal.
             * @default 33
             */
            resolution_confidence_pct: number;
            /** @description CQR-adjusted interval. Empirical marginal coverage under temporal drift: k8s 76.6% [74.0%, 79.1%], vscode 74.1% [69.4%, 78.3%]. None when conformal adjustments are unavailable. See ADR-0010. */
            resolution_interval_conformal?: components["schemas"]["ConformalIntervalResult"] | null;
            /**
             * Priority Guess
             * @enum {string}
             */
            priority_guess: "low" | "medium" | "high";
            /** Priority Rationale */
            priority_rationale: string;
            /** Suggested Assignee Class */
            suggested_assignee_class: string;
            /** Suggested Next Steps */
            suggested_next_steps: string[];
            /** Triage Summary */
            triage_summary: string;
            grounding?: components["schemas"]["GroundingAttribution"] | null;
            grounding_status?: components["schemas"]["GroundingStatus"] | null;
            /** @description LLM-declared source attribution (ADR-0020). None when the model omitted or malformed the block — counted as a compliance failure, never a request failure. */
            declared_attribution?: components["schemas"]["DeclaredAttribution"] | null;
            /** @description Selective-prediction gate (ADR-0021). None when conformal adjustments are unavailable for this repo (same fail-open policy as resolution_interval_conformal) — never blocks the response. */
            abstention_status?: components["schemas"]["AbstentionStatus"] | null;
        };
        /** TriageRequest */
        TriageRequest: {
            /**
             * Repo
             * @enum {string}
             */
            repo: "microsoft/vscode" | "kubernetes/kubernetes";
            /** Title */
            title: string;
            /**
             * Body
             * @default
             */
            body: string;
            /**
             * Issue Number
             * @default -1
             */
            issue_number: number;
            /**
             * Created At
             * @description ISO 8601 timestamp of issue creation. Defaults to request time if omitted.
             */
            created_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    triage_triage_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriagePlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    eval_summary_eval_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
